### ISSUE TITLE
Broken links to mascara-data.zip

### ISSUE THREAD

**Issue by pengler** [Mainack/MASCARA-passphrase-code-data#1]
The referenced  links (https://osf.io/dnrcj) to the mascara-data.zip file in the README.md seem to reference broken/unavailable resources.

**Comment by Mainack** [comment]
There was a permission issue on the osf.io repository. Should be fixed now.

**Comment by Mainack** [comment]
Closing this issue as the osf.io link is accessible now.

**Comment by pengler** [comment]
Links work now. Thank you for the quick fix.
